webexchange:
  registerConfirmationUrl: "http://localhost:4200/register-confirmation/"
  init:
    currencies: EUR, PLN, CZK, CAD, USD
    admin:
      email: admin@email.com
      username: admin
      password: admin



spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/webexchange"
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.mail.yahoo.com
    port: 587
    username: "webexchange.app@yahoo.com"
    password: "zqhrdvjgliedddsc" # Regular browser password is: Zaq1@wsx
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      starttls.required: true
