webexchange:
  registerConfirmationUrl: "http://localhost:8080/register-confirmation/"
  jwtConfig:
    secret: "WebExchange"
    durationInSeconds: 3600
  init: true
  initialCurrencies:
  - currencyCode: PLN
    country: Poland
  - currencyCode: EUR
    country: Germany, France, Italy
  - currencyCode: CZK
    country: Czech Republic
  - currencyCode: CAD
    country: Canada
  - currencyCode: USD
    country: USA
  admin:
    email: admin@email.com
    username: admin
    password: admin
  user:
    email: tester@mail.com
    username: tester
    password: tester

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/webexchange"
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.mail.yahoo.com
    port: 587
    username: "webexchange.app@yahoo.com"
    password: "zqhrdvjgliedddsc" # Regular browser password is: Zaq1@wsx
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      starttls.required: true
