spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/webexchange"
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: webexchange.app@gmail.com
    password: $WebExchange123
    properties.mail.smtp:
      auth: true
      starttls.enable: true

registerConfirmationUrl: "http://localhost:4200/register-confirmation/"
